version: "3.9"
services:
  fatman1:
    #restart: unless-stopped
    image: unificamproxy-jtrdev
    volumes:
      - /home/jtradmin/unifi-cam-proxy/client.pem:/client.pem
    command: unifi-cam-proxy -H 192.168.0.1 -i 10.10.2.46 -c /client.pem -t G4zOCdSHHZjByH8ajZARZgYHpLTHdYTG custom -s udp://10.10.2.46:5588
